global: 
  external_labels: 
    monitor: test-monitor
  scrape_interval: 5s
scrape_configs: 
  - 
    job_name: prometheus
    static_configs: 
      - 
        targets: 
          - "localhost:9090"
  -
    job_name: node-exporter
    static_configs:
      -
        targets:
          - "node-exporter:9100"
  - 
    job_name: my_docker_metrics
    static_configs:
      - 
        targets:
          - "docker-exporter:9104"